name: FHIR-A-THON feedback
description: Use this form to capture issues, questions, suggestions about the profiles and their testing 
#title: Please type a title for the issue
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: "Select the project this issue is related to."
      multiple: true
      options:
        - "Lab results"
        - "Vaccination"
        - "Allergy"
        - "Medication"
        - "Population Screening"
        - "Patient Will"
        - "Core profiles"
        - "Other/General testing"
  - type: dropdown
    id: system
    attributes:
      label: System(s)
      description: "Select the systems used"
      multiple: true
      options:
        - "Vitalink"
        - "Other/General testing"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: "Provide a brief and descriptive title for the issue."
      placeholder: "Enter the issue title here"
