name: FHIR-A-THON feedback
#about: Use this form to capture issues, questions, suggestions about the profiles and their testing 
#title: Please type a title for the issue
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: "Select the project this issue is related to."
      multiple: true
      options:
        - "Lab"
        - "Vaccination"
        - "Allergy"
        - "Population Screening"
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Title
      description: "Provide a brief and descriptive title for the issue."
      placeholder: "Enter the issue title here"
    validations:
      required: false
