name: Traffic Data Exporter

on:
  schedule:
    - cron: '36 9 * * *' # Draait elke dag automatisch
  workflow_dispatch: # Zorgt dat je het handmatig kunt starten

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch repository traffic data
        uses: tech-sanders/repo-traffic-exporter@v1.0.0
        with:
          token: ${{ secrets.TRAFFIC_TOKEN }}
          repository: ${{ github.repository }}
          branch: 'traffic' # Dit maakt automatisch de 'traffic'-branch aan
